import React, { useState, useEffect } from 'react';
import { X, Play, Terminal, Sparkles, CheckCircle2, RotateCcw, ShieldAlert, Cpu } from 'lucide-react';

interface McpTerminalModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const STAR_ME_FRAMES = [
  '🌌 🚀              🛸 ',
  '🌌  🚀            🛸  ',
  '🌌   🚀          🛸   ',
  '🌌    🚀        🛸    ',
  '🌌     🚀      🛸     ',
  '🌌      🚀    🛸      ',
  '🌌       🚀  🛸       ',
  '🌌        🚀🛸        ',
  '🌌         💥         ',
  '🌌        ✨ ✨       ',
  '🌌       ✨   ✨      ',
  '🌌      ✨     ✨     ',
  '🌌     ✨       ✨    ',
  '🌌                    '
];

export const McpTerminalModal: React.FC<McpTerminalModalProps> = ({
  isOpen,
  onClose
}) => {
  const [frameIndex, setFrameIndex] = useState(0);
  const [isRunning, setIsRunning] = useState(false);
  const [logs, setLogs] = useState<string[]>([
    '[SYSTEM] MasterCode MCP Stdio Server initialised.',
    '[TRANSPORT] StdioServerTransport bound to process.stdin / process.stdout.',
    '[TOOLS] Registered: read_workspace_file, write_workspace_file.',
    '[SECURITY] Sandbox active: ALLOWED_DIR = ./shared-workspace (Strict Traversal Check enabled).'
  ]);
  const [testFilePath, setTestFilePath] = useState('package.json');
  const [commandInput, setCommandInput] = useState('');

  // Star-me animation ticker
  useEffect(() => {
    if (!isRunning) return;
    const interval = setInterval(() => {
      setFrameIndex((prev) => (prev + 1) % STAR_ME_FRAMES.length);
    }, 120);
    return () => clearInterval(interval);
  }, [isRunning]);

  if (!isOpen) return null;

  const runStarMeTest = () => {
    setIsRunning(true);
    setLogs((prev) => [
      ...prev,
      '-------------------------------------------------------',
      '[STAR-ME] Invocando secuencia Multi-Modelo Vertex PSC...',
      '[AUTH] Conectando a extremo PSC 192.168.255.230...',
      '[CLAUDE] Consultando Claude Opus 4.6 en Vertex AI...',
      '[GEMINI] Resumiendo con Gemini 3.1 Pro...',
      '[HTTP] Puerto local 8080 listo para streaming de artefactos.'
    ]);

    setTimeout(() => {
      setIsRunning(false);
      setLogs((prev) => [
        ...prev,
        '[SUCCESS] ✓ Tarea completada. Artefactos asegurados en ./shared-workspace/images/',
        '[MCP-STDIO] Transmisión de buffers stdio cerrada limpiamente (exit code 0).'
      ]);
    }, 3500);
  };

  const handleTestTool = (toolName: 'read_workspace_file' | 'write_workspace_file') => {
    if (toolName === 'read_workspace_file') {
      if (testFilePath.includes('..') || testFilePath.startsWith('/etc')) {
        setLogs((prev) => [
          ...prev,
          `[MCP_CLIENT] -> call_tool: read_workspace_file { relativeFilePath: "${testFilePath}" }`,
          `[MCP_SERVER:SECURITY_ALERT] Acceso denegado: Intento de Directory Traversal detectado fuera de ./shared-workspace`,
          `[RESPONSE] isError: true`
        ]);
        return;
      }

      setLogs((prev) => [
        ...prev,
        `[MCP_CLIENT] -> call_tool: read_workspace_file { relativeFilePath: "${testFilePath}" }`,
        `[MCP_SERVER:STDIO] 200 OK - Leyendo buffer seguro (${testFilePath})...`,
        `[OUTPUT]: { "name": "master-code-mcp-server", "version": "1.0.0", "dependencies": { "@modelcontextprotocol/sdk": "^1.0.1" } }`,
        `[RESPONSE] isError: false`
      ]);
    } else {
      setLogs((prev) => [
        ...prev,
        `[MCP_CLIENT] -> call_tool: write_workspace_file { relativeFilePath: "${testFilePath}", content: "// Autogenerated by Agent 4" }`,
        `[MCP_SERVER:STDIO] Escritura atómica via archivo temporal .tmp completada.`,
        `[RESPONSE] Archivo escrito exitosamente.`
      ]);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-3xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="px-5 py-3.5 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-1.5 rounded-lg bg-indigo-500/20 text-indigo-400">
              <Terminal className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                <span>Terminal de Pruebas MCP Stdio & Animación Star-Me</span>
              </h3>
              <span className="text-[11px] text-slate-400 font-mono">
                Transporte: Standard Input/Output • Protocolo: MCP v1.0.1+
              </span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Animation Banner */}
        <div className="bg-slate-950/90 border-b border-slate-800 px-5 py-2.5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="text-xs font-mono text-cyan-400">
              {isRunning ? 'ESTADO: TRANSMITIENDO A TRAVÉS DEL HIPERESPACIO' : 'ESTADO: SERVIDOR MCP EN ESPERA'}
            </span>
            <div className="font-mono text-sm bg-slate-900 px-3 py-1 rounded-lg border border-slate-800 text-amber-300 min-w-[200px] text-center">
              {isRunning ? STAR_ME_FRAMES[frameIndex] : '🌌 🚀              🛸 '}
            </div>
          </div>

          <button
            onClick={runStarMeTest}
            disabled={isRunning}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-mono text-xs transition-all"
          >
            <Play className="w-3 h-3 fill-current" />
            <span>{isRunning ? 'Ejecutando Star-Me...' : 'Lanzar Prueba Star-Me'}</span>
          </button>
        </div>

        {/* MCP Tool test bar */}
        <div className="p-3 bg-slate-900/80 border-b border-slate-800 flex flex-wrap items-center gap-2 text-xs">
          <span className="font-mono text-slate-400">call_tool:</span>
          <input
            type="text"
            value={testFilePath}
            onChange={(e) => setTestFilePath(e.target.value)}
            className="bg-slate-950 border border-slate-700 rounded px-2.5 py-1 text-xs font-mono text-slate-200 focus:outline-none focus:border-cyan-500"
            placeholder="relativeFilePath (ej. package.json o ../etc/passwd)"
          />

          <button
            onClick={() => handleTestTool('read_workspace_file')}
            className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-cyan-300 border border-cyan-700/50 font-mono text-[11px]"
          >
            read_workspace_file
          </button>

          <button
            onClick={() => handleTestTool('write_workspace_file')}
            className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-emerald-300 border border-emerald-700/50 font-mono text-[11px]"
          >
            write_workspace_file
          </button>

          <button
            onClick={() => setLogs([])}
            className="ml-auto text-slate-500 hover:text-slate-300 font-mono text-[11px]"
          >
            Limpiar logs
          </button>
        </div>

        {/* Console Log Area */}
        <div className="flex-1 p-4 bg-slate-950 font-mono text-xs text-slate-300 overflow-y-auto space-y-1.5 min-h-[260px] max-h-[380px]">
          {logs.map((log, idx) => (
            <div
              key={idx}
              className={`leading-relaxed ${
                log.includes('SECURITY_ALERT') || log.includes('denegado')
                  ? 'text-rose-400 font-bold'
                  : log.includes('SUCCESS') || log.includes('✓')
                  ? 'text-emerald-400'
                  : log.includes('[STAR-ME]')
                  ? 'text-cyan-300'
                  : log.includes('[MCP_CLIENT]')
                  ? 'text-indigo-300'
                  : 'text-slate-300'
              }`}
            >
              {log}
            </div>
          ))}
        </div>

        {/* Modal Footer */}
        <div className="p-3 bg-slate-950 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400 font-mono">
          <span>Transporte de canal: Stdio (sin sockets de red expuestos)</span>
          <button
            onClick={onClose}
            className="px-3 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200"
          >
            Cerrar
          </button>
        </div>
      </div>
    </div>
  );
};
